spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: 'jdbc:mysql://elonhai.com:3306/user_center?useSSL=false'
    username: ahai
    password: 8m4FB35PAim6HD4H
  # session 失效时间
  session:
    timeout: 86400
server:
  address: 0.0.0.0
